import os

PATH_HOME = os.path.join("UI", "SportArea-Home.ui")
PATH_LOGIN = os.path.join("UI", "SportArea-LogIn.ui")
PATH_REGISTER = os.path.join("UI", "SportArea-SignIn.ui")
PATH_EMAIL_RECUPERO = os.path.join("UI", "SportArea-EmailRecupero.ui")
PATH_CODICE_RECUPERO = os.path.join("UI", "SportArea-CodiceRecupero.ui")
PATH_HOME_CLIENTE = os.path.join("UI", "SportArea-Cliente.ui")
PATH_ACCOUNT = os.path.join("UI", "SportArea-Account.ui")
PATH_MODIFICA_ACCOUNT = os.path.join("UI", "SportArea-ModificaAccount.ui")
PATH_PORTAFOGLIO = os.path.join("UI", "SportArea-Portafoglio.ui")
PATH_AMICI_ATTIVI = os.path.join("UI", "SportArea-ListaAmici.ui")
PATH_AMICI_ATTESA = os.path.join("UI", "SportArea-Richieste.ui")
PATH_MENU_AMICIZIA = os.path.join("UI", "SportArea-Amici.ui")
PATH_CERCA_PRENOTAZIONI = os.path.join("UI", "SportArea-Prenotazione.ui")